site_name: 成人版抖音·(中国区)官方网站-入口
site_author: 成人版抖音·(中国区)官方网站-入口
site_description: 成人版抖音是专为18岁以上用户设计的短视频平台，提供适合成年人的内容社区和隐私保护功能，打造健康的成人社交空间。
theme:
  name: readthedocs
nav:
  - Home: index.md
  - About: about.md
  - Features: features.md
  - Contact: contact.md
